### ISSUE TITLE
Correctly implement databinding for WTransform and Vector3

### ISSUE THREAD

**Issue by Sage-of-Mirrors** [LordNed/Winditor#1]
`WTransform` is currently hooked up to the UI by way of a `BindingVector3`. Currently, it only has half the functionality required; it will correctly display the selected object's `WTransform` properties, and update as the object is moved in the viewport, but manual changes to the UI are not propagated back to the selected object.

Thoughts:
* The UI may not be propagating correctly because of a mismatch on what is listening to which `OnPropertyChanged()` events.
* It may be better to investigate other ways of making this work.

**Comment by LagoLunatic** [comment]
Update: It works for position and scale now, but not rotation.
