### ISSUE TITLE
Prevent collision hierarchy treeview from closing nodes on double click

### ISSUE THREAD

**Issue by Sage-of-Mirrors** [LordNed/Winditor#14]
Double clicking in the treeview for the collision hierarchy selects all triangles belonging to that node, but the default behavior of the treeview is to toggle the node's expansion status when double clicked. This behavior must be overriden to prevent double clicking from closing or opening the nodes.

**Comment by LagoLunatic** [comment]
Just tested and this bug doesn't happen anymore.
