### ISSUE TITLE
Ensure that collision meshes are destroyed when a room is unloaded.

### ISSUE THREAD

**Issue by Sage-of-Mirrors** [LordNed/Winditor#15]
A crash with WCollisionMesh's shader revealed that the collision mesh is not currently being disposed properly when a map is unloaded. This causes conflicts within OpenTK, which ultimately leads to a crash when the shader attempts to get disposed twice.

**Comment by LagoLunatic** [comment]
Fixed in 6efa1270211ebaf6e217eea68b7583d79eb7c4f8
