### ISSUE TITLE
Crash when clicking if Root Directory not set

### ISSUE THREAD

**Issue by LagoLunatic** [LordNed/Winditor#17]
If you click anywhere in the 3D view when Root Directory is set to nothing or to an incorrect directory, [this line](https://github.com/LordNed/Winditor/blob/e362d0b71f5ab6c6712fc146ac53e2ff01770a46/Editor/Editor/Entities/VisibleDOMNode.cs#L157) crashes because m_objRender is null.

**Comment by Mallos31** [comment]
It does it to me even with a proper Root Directory set. I can get things to render, but then it crashes.
