### ISSUE TITLE
Camera Speed up 

### ISSUE THREAD

**Issue by RealShanks** [LordNed/Winditor#26]
Camera often spawns far away from objects (in viewport) and the camera movement speed (editor) makes editing a slow process.

**Comment by LagoLunatic** [comment]
In the left sidebar, right click on the name of a room or object and select "Go Here" to instantly teleport the camera in front of it.

**Comment by RealShanks** [comment]
> In the left sidebar, right click on the name of a room or object and select "Go Here" to instantly teleport the camera in front of it.
> Edit: Also, holding down shift increases the camera's movement speed
> Thanks so much! Sorry to have bothered you :)
