### ISSUE TITLE
WARNING [m_Do_dvd_thread.cpp:576]  can't open: [/res/object/.arc]

### ISSUE THREAD

**Issue by somethingoranother22** [LordNed/Winditor#28]
This message appears when adding actors to maps. Actors added don't load during playtesting. The issue is not present when editing pre-existing actors. 

![20211108_183621](https://user-images.githubusercontent.com/93954029/140837386-a20078b3-65a0-4925-ae67-15e6842dfb31.jpg)

**Comment by LagoLunatic** [comment]
This means that an actor you added has the wrong parameters set. Say what actor you added and show a screenshot of the exact parameters you have set.

**Comment by LagoLunatic** [comment]
Try changing Unknown_4 to various different values and at least one or two of them will work.
