### ISSUE TITLE
Vertex Colors on export to Collada are badly messed up and do not match in-editor

### ISSUE THREAD

**Issue by WereTech** [LordNed/Winditor#30]
Any model that I attempt to export will have fractured vertex colors that are mostly not even blended together between faces, and seem to be forced in greyscale as it seems there is color in the map, but only a range of white-black in the Collada.

Blender view: ![DogZzOm](https://user-images.githubusercontent.com/17415815/152650695-e7d7a99d-a062-4566-82f2-915dd08662eb.png)

Winditor view: ![rY3w484](https://user-images.githubusercontent.com/17415815/152650716-1c1657ae-1e9e-4455-a851-dd70806519c0.png)

**Comment by Thaums** [comment]
This issue is actually solved in this fork of SuperBMD:
https://github.com/RenolY2/SuperBMD

However I haven't found a converter that doesn't break the UVs on certain maps:
![image](https://user-images.githubusercontent.com/21028062/164798006-c0d34df3-69f8-4fc9-8c99-d3d467330258.png)

So it seems like lossy map conversions are an issue no matter what converter you're using

**Comment by WereTech** [comment]
> This issue is actually solved in this fork of SuperBMD: https://github.com/RenolY2/SuperBMD
> 
> However I haven't found a converter that doesn't break the UVs on certain maps.
> 
> So it seems like lossy map conversions are an issue no matter what converter you're using

Thanks for showing me this fork, there seems to be a lot of different SuperBMD versions that show up to solve different problems that I'm unaware of xD.
Also some textures will look "broken" because Nintendo likes to make use of mirrored textures, either once or twice mirrored on the X or Y axis. So all it takes to fix that is by using an image editor and copy/pasting then flipping it vertically or horizontally, and possibly some UV scaling too depending if your 3d editor will attempt to change the scaling based on image size or not.

**Comment by LagoLunatic** [comment]
The messed up vertex colors should be fixed by d288f716385e0dc1e14c2c56c16fb205770a33ad and the texture wrap modes being wrong should be fixed by 1f0798fd2164b584c4cbe34cb9869976a047a971.
