### ISSUE TITLE
Back to Rom?

### ISSUE THREAD

**Issue by Enaisreal2401** [LordNed/Winditor#39]
Hi, I am a major noob when it comes to modding, and I looked everywhere for this, but couldn't find an answer. I don't know if I'm blind, or if this is common knowledge, but after you turn the original copy of a rom into a folder, how do you turn the folder back to a rom?

**Comment by LagoLunatic** [comment]
GCFT https://github.com/LagoLunatic/GCFT

Note that you don't need to rebuild the GCM during testing, only when you're gonna make a patch to share your mod
