### ISSUE TITLE
Retain all archive data for exporting/saving

### ISSUE THREAD

**Issue by Sage-of-Mirrors** [LordNed/Winditor#6]
At this time, any data other than room models and entity data is discarded. Additionally, only entity data is saved to file. While this is usable, it is inefficient.

The program should keep track of all the data that it loads so that it can save it back out, either "compiled" as archives or "raw" as the directory structure of the archives. The data should probably be stored in the `World` class..

**Comment by LagoLunatic** [comment]
Seems to have been fixed at some point
